import crypto from "crypto";
import { inventorySeed, menuSeed } from "./catalog";

const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value));
const isoHoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
const isoDaysAgo = (days: number, extraHours = 0) =>
  new Date(Date.now() - (days * 24 + extraHours) * 60 * 60 * 1000).toISOString();

const hashPassword = (password: string) => {
  const salt = "chicken-house-seed-salt";
  const hash = crypto.scryptSync(password, salt, 64).toString("hex");
  return `${salt}:${hash}`;
};

export const createDb = () => ({
  staff: [
    { id: 1, name: "Ahmed Khan", role: "General Staff", status: "Active", shift: "Morning", salary: 75000, joinDate: "2021-05-12", email: "ahmed@chickenhouse.com", phone: "+92 300 1111111", address: "Kitchen Block, Renala Khurd", emergencyContact: "+92 301 1111111", userAccountId: "demo-staff-2", department: "Operations", leaveBalance: 15, performanceScore: 4.8 },
    { id: 2, name: "Zubair Ali", role: "Manager", status: "Active", shift: "Evening", salary: 65000, joinDate: "2022-02-20", email: "zubair@chickenhouse.com", phone: "+92 300 2222222", address: "Club Road, Renala Khurd", emergencyContact: "+92 301 2222222", userAccountId: "demo-manager-1", department: "Management", leaveBalance: 18, performanceScore: 4.9 },
    { id: 3, name: "Bilal Ahmed", role: "Rider", status: "Active", shift: "Night", salary: 35000, joinDate: "2023-01-15", email: "bilal@chickenhouse.com", phone: "+92 300 3333333", address: "Main Bazaar, Renala Khurd", emergencyContact: "+92 301 3333333", userAccountId: "demo-rider-1", department: "Delivery", leaveBalance: 20, performanceScore: 4.5 },
    { id: 4, name: "Salman Malik", role: "General Staff", status: "On Leave", shift: "Morning", salary: 40000, joinDate: "2022-11-10", email: "salman@chickenhouse.com", phone: "+92 300 4444444", address: "Mitchell Road, Renala Khurd", emergencyContact: "+92 301 4444444", userAccountId: "demo-staff-3", department: "Operations", leaveBalance: 5, performanceScore: 4.6 },
    { id: 5, name: "Waleed Akram", role: "Rider", status: "Active", shift: "Morning", salary: 42000, joinDate: "2023-07-05", email: "waleed@chickenhouse.com", phone: "+92 300 5555555", address: "Canal View, Renala Khurd", emergencyContact: "+92 301 5555555", userAccountId: "demo-rider-2", department: "Delivery", leaveBalance: 16, performanceScore: 4.4 },
    { id: 6, name: "Ammar Tariq", role: "General Staff", status: "Active", shift: "Evening", salary: 32000, joinDate: "2024-01-11", email: "ammar@chickenhouse.com", phone: "+92 300 6666666", address: "Railway Colony, Renala Khurd", emergencyContact: "+92 301 6666666", userAccountId: "demo-staff-1", department: "Operations", leaveBalance: 14, performanceScore: 4.2 },
  ],
  attendance: [
    { id: "ATT-1001", staffId: 1, staffName: "Ahmed Khan", date: "2026-05-18", clockIn: "08:45", clockOut: "17:30", status: "Present", workHours: 8.75, notes: "" },
    { id: "ATT-1002", staffId: 2, staffName: "Zubair Ali", date: "2026-05-18", clockIn: "09:00", clockOut: "18:00", status: "Present", workHours: 9, notes: "" },
    { id: "ATT-1003", staffId: 3, staffName: "Bilal Ahmed", date: "2026-05-18", clockIn: "22:00", clockOut: "", status: "Present", workHours: 0, notes: "Night shift ongoing" },
    { id: "ATT-1004", staffId: 4, staffName: "Salman Malik", date: "2026-05-18", clockIn: "", clockOut: "", status: "Leave", workHours: 0, notes: "Approved sick leave" },
    { id: "ATT-1005", staffId: 1, staffName: "Ahmed Khan", date: "2026-05-17", clockIn: "08:50", clockOut: "17:45", status: "Present", workHours: 8.92, notes: "" },
    { id: "ATT-1006", staffId: 2, staffName: "Zubair Ali", date: "2026-05-17", clockIn: "09:15", clockOut: "18:10", status: "Late", workHours: 8.92, notes: "Traffic delay" },
  ],
  leaveRequests: [
    { id: "LV-1001", staffId: 4, staffName: "Salman Malik", leaveType: "Sick", startDate: "2026-05-18", endDate: "2026-05-20", days: 3, reason: "Flu and fever", status: "Approved", approvedBy: "Zubair Ali", approvedAt: "2026-05-17T10:30:00Z", rejectionReason: "" },
    { id: "LV-1002", staffId: 3, staffName: "Bilal Ahmed", leaveType: "Casual", startDate: "2026-05-25", endDate: "2026-05-25", days: 1, reason: "Personal work", status: "Pending", approvedBy: "", approvedAt: "", rejectionReason: "" },
    { id: "LV-1003", staffId: 1, staffName: "Ahmed Khan", leaveType: "Annual", startDate: "2026-06-01", endDate: "2026-06-05", days: 5, reason: "Family vacation", status: "Pending", approvedBy: "", approvedAt: "", rejectionReason: "" },
  ],
  payroll: [
    { id: "PAY-1001", staffId: 1, staffName: "Ahmed Khan", month: "April", year: 2026, baseSalary: 75000, bonus: 5000, deductions: 2000, netSalary: 78000, workingDays: 26, presentDays: 26, absentDays: 0, leaveDays: 0, status: "Paid", paidAt: "2026-05-01T10:00:00Z", paymentMethod: "Bank Transfer" },
    { id: "PAY-1002", staffId: 2, staffName: "Zubair Ali", month: "April", year: 2026, baseSalary: 65000, bonus: 8000, deductions: 1500, netSalary: 71500, workingDays: 26, presentDays: 25, absentDays: 0, leaveDays: 1, status: "Paid", paidAt: "2026-05-01T10:00:00Z", paymentMethod: "Bank Transfer" },
    { id: "PAY-1003", staffId: 3, staffName: "Bilal Ahmed", month: "April", year: 2026, baseSalary: 35000, bonus: 2000, deductions: 500, netSalary: 36500, workingDays: 26, presentDays: 24, absentDays: 2, leaveDays: 0, status: "Paid", paidAt: "2026-05-01T10:00:00Z", paymentMethod: "Cash" },
    { id: "PAY-1004", staffId: 4, staffName: "Salman Malik", month: "April", year: 2026, baseSalary: 40000, bonus: 1000, deductions: 800, netSalary: 40200, workingDays: 26, presentDays: 23, absentDays: 1, leaveDays: 2, status: "Paid", paidAt: "2026-05-01T10:00:00Z", paymentMethod: "Bank Transfer" },
  ],
  shiftSchedules: [
    { id: "SH-1001", staffId: 1, staffName: "Ahmed Khan", date: "2026-05-19", shiftType: "Morning", startTime: "09:00", endTime: "17:00", notes: "" },
    { id: "SH-1002", staffId: 2, staffName: "Zubair Ali", date: "2026-05-19", shiftType: "Evening", startTime: "14:00", endTime: "22:00", notes: "" },
    { id: "SH-1003", staffId: 3, staffName: "Bilal Ahmed", date: "2026-05-19", shiftType: "Night", startTime: "22:00", endTime: "06:00", notes: "" },
    { id: "SH-1004", staffId: 4, staffName: "Salman Malik", date: "2026-05-19", shiftType: "Off", startTime: "", endTime: "", notes: "Sick leave" },
  ],
  performanceReviews: [
    { id: "PR-1001", staffId: 1, staffName: "Ahmed Khan", reviewDate: "2026-04-15", reviewPeriod: "Q1 2026", punctuality: 5, quality: 5, teamwork: 4, communication: 5, overallScore: 4.8, strengths: "Excellent cooking skills, great leadership", improvements: "Time management during rush hours", reviewedBy: "Zubair Ali" },
    { id: "PR-1002", staffId: 2, staffName: "Zubair Ali", reviewDate: "2026-04-15", reviewPeriod: "Q1 2026", punctuality: 5, quality: 5, teamwork: 5, communication: 5, overallScore: 4.9, strengths: "Outstanding management, customer relations", improvements: "Delegate more tasks", reviewedBy: "Owner Admin" },
    { id: "PR-1003", staffId: 3, staffName: "Bilal Ahmed", reviewDate: "2026-04-15", reviewPeriod: "Q1 2026", punctuality: 4, quality: 5, teamwork: 4, communication: 5, overallScore: 4.5, strengths: "Fast delivery, customer friendly", improvements: "Punctuality needs improvement", reviewedBy: "Zubair Ali" },
  ],
  staffNotices: [
    {
      id: "NTC-1001",
      title: "Weekend Dinner Rush Plan",
      message: "All evening staff must report 15 minutes early on Friday and Saturday. Kitchen and counter teams should confirm station readiness before 6 PM.",
      audience: ["staff", "manager"],
      createdAt: isoHoursAgo(20),
      seenBy: [2, 4],
    },
    {
      id: "NTC-1002",
      title: "Delivery Safety Reminder",
      message: "Riders must confirm helmet, fuel, and phone charge before every dispatch. Failed delivery reasons should be logged immediately after return.",
      audience: ["rider", "manager"],
      createdAt: isoHoursAgo(14),
      seenBy: [2],
    },
    {
      id: "NTC-1003",
      title: "Low Stock Monitoring",
      message: "Operations staff should flag cheese, chicken, and fries stock before the lunch rush so the manager can raise purchase requests on time.",
      audience: ["staff", "manager"],
      createdAt: isoHoursAgo(10),
      seenBy: [],
    },
  ],
  staffRequests: [
    {
      id: "REQ-1001",
      staffId: 3,
      staffName: "Bilal Ahmed",
      category: "Attendance Correction",
      subject: "Clock-out missing for 2026-05-18",
      message: "Night shift was completed but clock-out did not save. Please verify and correct the record.",
      status: "Pending",
      createdAt: isoHoursAgo(9),
      resolvedAt: "",
    },
  ],
  activityLogs: [
    {
      id: "ACT-1001",
      staffId: 4,
      staffName: "Salman Malik",
      role: "staff",
      action: "Attendance marked",
      detail: "Attendance marked at 09:03 AM.",
      createdAt: isoHoursAgo(6),
    },
    {
      id: "ACT-1002",
      staffId: 1,
      staffName: "Ahmed Khan",
      role: "staff",
      action: "Order updated",
      detail: "Order ORD-1001 moved to Preparing.",
      createdAt: isoHoursAgo(5),
    },
    {
      id: "ACT-1003",
      staffId: 3,
      staffName: "Bilal Ahmed",
      role: "rider",
      action: "Delivery updated",
      detail: "Order ORD-1002 marked Out for Delivery.",
      createdAt: isoHoursAgo(3),
    },
  ],
  inventory: clone(inventorySeed),
  vendorPurchases: [
    {
      id: "VND-1001",
      vendorName: "Mitchell Market Traders",
      itemName: "Fresh Chicken",
      unit: "kg",
      quotedPrice: 650,
      targetPrice: 620,
      quantityReceived: 40,
      minimumOrderQuantity: 20,
      billAmount: 26000,
      amountPaid: 18000,
      discountCut: 1000,
      purchaseDate: isoHoursAgo(22),
      status: "Partially Paid",
      notes: "Rate negotiated after comparing two nearby suppliers.",
    },
    {
      id: "VND-1002",
      vendorName: "Punjab Dairy Point",
      itemName: "Cheese",
      unit: "kg",
      quotedPrice: 1450,
      targetPrice: 1400,
      quantityReceived: 12,
      minimumOrderQuantity: 8,
      billAmount: 17400,
      amountPaid: 17400,
      discountCut: 600,
      purchaseDate: isoDaysAgo(2, 5),
      status: "Paid",
      notes: "Weekend wholesale rate with full payment cleared.",
    },
    {
      id: "VND-1003",
      vendorName: "Okara Fresh Produce",
      itemName: "Lettuce",
      unit: "kg",
      quotedPrice: 180,
      targetPrice: 160,
      quantityReceived: 14,
      minimumOrderQuantity: 10,
      billAmount: 2520,
      amountPaid: 0,
      discountCut: 0,
      purchaseDate: isoHoursAgo(18),
      status: "Unpaid",
      notes: "Hold for final market comparison before clearing bill.",
    },
  ],
  finance: [
    { id: "TX-101", type: "Credit", amount: 2560, source: "Order CH-12345", date: isoHoursAgo(3), category: "Sales" },
    { id: "TX-102", type: "Debit", amount: 15000, source: "Chicken Procurement", date: isoHoursAgo(8), category: "Inventory" },
    { id: "TX-103", type: "Credit", amount: 5200, source: "Order CH-12346", date: isoHoursAgo(11), category: "Sales" },
    { id: "TX-104", type: "Debit", amount: 2500, source: "Utility Bill (Gas)", date: isoDaysAgo(1, 4), category: "Utilities" },
  ],
  orders: [
    {
      id: "ORD-1001",
      customer: "Farhan Ali",
      customerEmail: "farhan@chickenhouse.com",
      customerPhone: "+92 300 1234567",
      deliveryAddress: "House #123, Block B, Renala Khurd",
      items: "2x Chicken Burger, 1x Fries",
      subtotal: 1450,
      deliveryFee: 100,
      total: 1550,
      status: "Preparing",
      time: isoHoursAgo(2),
      type: "Delivery",
      paymentMethod: "Wallet",
      notes: "Call on arrival.",
      details: [
        { name: "Chicken Burger", quantity: 2, price: 450, variantLabel: "Moderate" },
        { name: "Fries", quantity: 1, price: 250, variantLabel: "Moderate" },
      ],
      assignedStaffId: 1,
      assignedStaffName: "Ahmed Khan",
      assignedRole: "staff",
    },
    {
      id: "ORD-1002",
      customer: "Sara Ahmed",
      customerEmail: "sara@example.com",
      customerPhone: "+92 321 5558811",
      deliveryAddress: "Main Bazaar Road, Renala Khurd",
      items: "1x Mixed BBQ Platter",
      subtotal: 2300,
      deliveryFee: 150,
      total: 2450,
      status: "Out for Delivery",
      time: isoHoursAgo(3),
      type: "Delivery",
      paymentMethod: "Cash on Delivery",
      details: [
        { name: "Mixed BBQ Platter (Chicken, Mutton, Beef)", quantity: 1, price: 1000, variantLabel: "Premium" },
      ],
      assignedStaffId: 3,
      assignedStaffName: "Bilal Ahmed",
      assignedRole: "rider",
    },
    {
      id: "ORD-1003",
      customer: "Farhan Ali",
      customerEmail: "farhan@chickenhouse.com",
      customerPhone: "+92 300 1234567",
      deliveryAddress: "Table 6, Ground Floor",
      items: "3x Chicken Tikka",
      subtotal: 1950,
      deliveryFee: 0,
      total: 1950,
      status: "Pending",
      time: isoHoursAgo(4),
      type: "Dine-in",
      paymentMethod: "Cash",
      notes: "Serve extra dip on the side.",
      details: [
        { name: "Chicken Tikka", quantity: 3, price: 600, variantLabel: "Premium" },
      ],
      assignedStaffId: 4,
      assignedStaffName: "Salman Malik",
      assignedRole: "staff",
    },
    {
      id: "ORD-1004",
      customer: "Zainab Bibi",
      customerEmail: "zainab@example.com",
      customerPhone: "+92 345 7788899",
      deliveryAddress: "Takeaway Counter Pickup",
      items: "1x BBQ Chicken Burger",
      subtotal: 1250,
      deliveryFee: 0,
      total: 1250,
      status: "Delivered",
      time: isoHoursAgo(6),
      type: "Takeaway",
      paymentMethod: "Card on Delivery",
      details: [
        { name: "BBQ Chicken Burger", quantity: 1, price: 700, variantLabel: "Premium" },
      ],
      assignedStaffId: 4,
      assignedStaffName: "Salman Malik",
      assignedRole: "staff",
    },
  ],
  customers: [
    {
      id: "demo-user-1",
      name: "Farhan Ali",
      email: "farhan@chickenhouse.com",
      phone: "+92 300 1234567",
      address: "House #123, Block B, Renala Khurd",
      city: "Renala Khurd",
      memberSince: "2024",
      loyaltyPoints: 1240,
      walletBalance: 12450,
      favoriteCategory: "BBQ & Desi",
      orderCount: 18,
      avatarInitials: "FA",
      preferences: {
        notifications: true,
        promotions: true,
        orderUpdates: true,
        darkAlerts: false,
      },
      addresses: [
        {
          id: "ADDR-1",
          label: "Home",
          line: "House #123, Block B, Renala Khurd",
          note: "Ring bell at gate",
        },
        {
          id: "ADDR-2",
          label: "Office",
          line: "Mitchell's Market Road, Renala Khurd",
          note: "Delivery after 1 PM",
        },
      ],
      wishlist: [
        {
          id: "WISH-1",
          name: "Chicken Karahi",
          category: "Desi (Pakistani)",
          price: 900,
          image: "https://cdn.pixabay.com/photo/2022/06/10/05/20/chicken-karahi-7253714_1280.jpg",
        },
        {
          id: "WISH-2",
          name: "BBQ Chicken Pizza",
          category: "Pizza",
          price: 900,
          image: "https://cdn.pixabay.com/photo/2017/12/09/08/18/pizza-3007395_1280.jpg",
        },
        {
          id: "WISH-3",
          name: "Mint Margarita",
          category: "Drinks",
          price: 200,
          image: "https://cdn.pixabay.com/photo/2017/05/19/20/32/lemonade-2328925_1280.jpg",
        },
      ],
      walletTransactions: [
        { id: "W-101", type: "Spent", amount: 2560, reason: "Order ORD-1001", time: isoHoursAgo(7) },
        { id: "W-102", type: "Top-up", amount: 5000, reason: "Bank Transfer", time: isoDaysAgo(1, 2) },
        { id: "W-103", type: "Spent", amount: 850, reason: "Order ORD-0991", time: isoDaysAgo(3, 1) },
      ],
      activity: [
        "Your order ORD-1001 is now preparing.",
        "Wallet topped up successfully via bank transfer.",
        "Chicken Karahi was added to your wishlist.",
      ],
    },
  ],
  userAccounts: [
    {
      id: "demo-admin-1",
      name: "Owner Admin",
      email: "admin@chickenhouse.com",
      passwordHash: hashPassword("admin123"),
      adminVisiblePassword: "admin123",
      role: "admin",
      provider: "email",
      status: "Active",
      phone: "+92 345 7493339",
      memberSince: "2024",
      emailVerified: true,
      lastLoginAt: "",
      avatarUrl: "",
      avatarInitials: "OA",
      customerProfileId: "",
      preferences: {
        notifications: true,
        promotions: true,
        orderUpdates: true,
        language: "en",
        theme: "restaurant-dark",
      },
    },
    {
      id: "demo-manager-1",
      name: "Zubair Ali",
      email: "zubair@chickenhouse.com",
      passwordHash: hashPassword("manager123"),
      adminVisiblePassword: "manager123",
      role: "manager",
      provider: "email",
      status: "Active",
      phone: "+92 300 2222222",
      staffMemberId: 2,
      memberSince: "2024",
      emailVerified: true,
      lastLoginAt: "",
      avatarUrl: "",
      avatarInitials: "ZA",
      customerProfileId: "",
      preferences: {
        notifications: true,
        promotions: true,
        orderUpdates: true,
        language: "en",
        theme: "restaurant-dark",
      },
    },
    {
      id: "demo-rider-1",
      name: "Bilal Ahmed",
      email: "bilal@chickenhouse.com",
      passwordHash: hashPassword("rider123"),
      adminVisiblePassword: "rider123",
      role: "rider",
      provider: "email",
      status: "Active",
      phone: "+92 300 3333333",
      staffMemberId: 3,
      memberSince: "2024",
      emailVerified: true,
      lastLoginAt: "",
      avatarUrl: "",
      avatarInitials: "BA",
      customerProfileId: "",
      preferences: {
        notifications: true,
        promotions: true,
        orderUpdates: true,
        language: "en",
        theme: "restaurant-dark",
      },
    },
    {
      id: "demo-rider-2",
      name: "Waleed Akram",
      email: "waleed@chickenhouse.com",
      passwordHash: hashPassword("rider123"),
      adminVisiblePassword: "rider123",
      role: "rider",
      provider: "email",
      status: "Active",
      phone: "+92 300 5555555",
      staffMemberId: 5,
      memberSince: "2024",
      emailVerified: true,
      lastLoginAt: "",
      avatarUrl: "",
      avatarInitials: "WA",
      customerProfileId: "",
      preferences: {
        notifications: true,
        promotions: true,
        orderUpdates: true,
        language: "en",
        theme: "restaurant-dark",
      },
    },
    {
      id: "demo-staff-2",
      name: "Ahmed Khan",
      email: "ahmed@chickenhouse.com",
      passwordHash: hashPassword("staff123"),
      adminVisiblePassword: "staff123",
      role: "staff",
      provider: "email",
      status: "Active",
      phone: "+92 300 1111111",
      staffMemberId: 1,
      memberSince: "2024",
      emailVerified: true,
      lastLoginAt: "",
      avatarUrl: "",
      avatarInitials: "AK",
      customerProfileId: "",
      preferences: {
        notifications: true,
        promotions: true,
        orderUpdates: true,
        language: "en",
        theme: "restaurant-dark",
      },
    },
    {
      id: "demo-staff-1",
      name: "Ammar Tariq",
      email: "ammar@chickenhouse.com",
      passwordHash: hashPassword("staff123"),
      adminVisiblePassword: "staff123",
      role: "staff",
      provider: "email",
      status: "Active",
      phone: "+92 300 6666666",
      staffMemberId: 6,
      memberSince: "2024",
      emailVerified: true,
      lastLoginAt: "",
      avatarUrl: "",
      avatarInitials: "AT",
      customerProfileId: "",
      preferences: {
        notifications: true,
        promotions: true,
        orderUpdates: true,
        language: "en",
        theme: "restaurant-dark",
      },
    },
    {
      id: "demo-staff-3",
      name: "Salman Malik",
      email: "salman@chickenhouse.com",
      passwordHash: hashPassword("staff123"),
      adminVisiblePassword: "staff123",
      role: "staff",
      provider: "email",
      status: "Active",
      phone: "+92 300 4444444",
      staffMemberId: 4,
      memberSince: "2024",
      emailVerified: true,
      lastLoginAt: "",
      avatarUrl: "",
      avatarInitials: "SM",
      customerProfileId: "",
      preferences: {
        notifications: true,
        promotions: true,
        orderUpdates: true,
        language: "en",
        theme: "restaurant-dark",
      },
    },
    {
      id: "demo-user-1",
      name: "Farhan Ali",
      email: "farhan@chickenhouse.com",
      passwordHash: hashPassword("user123"),
      adminVisiblePassword: "",
      role: "user",
      provider: "email",
      status: "Active",
      phone: "+92 300 1234567",
      memberSince: "2024",
      emailVerified: true,
      lastLoginAt: "",
      avatarUrl: "",
      avatarInitials: "FA",
      customerProfileId: "demo-user-1",
      preferences: {
        notifications: true,
        promotions: true,
        orderUpdates: true,
        language: "en",
        theme: "restaurant-dark",
      },
    },
  ],
  authSessions: [],
  bookings: [],
  contactMessages: [],
  assistantConversations: [
    {
      id: "CHAT-1001",
      customerName: "Farhan Ali",
      customerNumber: "+92 300 1112233",
      adminNumber: "+92 345 7493339",
      channel: "WhatsApp",
      status: "Bot Active",
      startedAt: "2026-03-18T08:20:00Z",
      updatedAt: "2026-03-18T08:25:00Z",
      messages: [
        {
          id: "MSG-1",
          role: "customer",
          text: "Assalam o Alaikum, location send kar dein.",
          createdAt: "2026-03-18T08:20:00Z",
        },
        {
          id: "MSG-2",
          role: "assistant",
          text: "Wa Alaikum Assalam. Chicken House is near Mitchell's Fair Price Shop, GT Road, Renala Khurd, Okara. We are open 11:00 AM to 12:00 AM.",
          createdAt: "2026-03-18T08:20:10Z",
        },
        {
          id: "MSG-3",
          role: "customer",
          text: "Menu pictures aur platter suggestion bhi bhej dein.",
          createdAt: "2026-03-18T08:24:00Z",
        },
        {
          id: "MSG-4",
          role: "assistant",
          text: "I can share Chicken Karahi, Chicken Biryani, Chicken Tikka, and BBQ Chicken Pizza pictures and suggest a 2-person or 4-person platter.",
          createdAt: "2026-03-18T08:25:00Z",
        },
      ],
    },
  ],
  reviews: [],
  promotions: [],
  notifications: [],
  jobApplications: [],
  riders: [
    { id: "RD-001", name: "Bilal Ahmed", phone: "+92 333 4880841", status: "Available", shift: "Evening", vehicleType: "Bike", plateNumber: "OKR-1234", zone: "Renala Khurd", rating: 4.8, activeOrders: 0 },
    { id: "RD-002", name: "Usman Ghani", phone: "+92 333 4880842", status: "On Delivery", shift: "Day", vehicleType: "Bike", plateNumber: "OKR-5678", zone: "Okara City", rating: 4.6, activeOrders: 1 },
    { id: "RD-003", name: "Ali Raza", phone: "+92 333 4880843", status: "Offline", shift: "Night", vehicleType: "Bike", plateNumber: "OKR-9012", zone: "GT Road", rating: 4.9, activeOrders: 0 },
  ],
  jobOpenings: [
    { id: "JOB-chef", title: "Chef / Cook", department: "Kitchen", type: "Full-time", location: "Renala Khurd", description: "Prepare BBQ, karahi, and fast-food items to Chicken House standards.", requirements: ["2+ years kitchen experience", "Knowledge of desi & fast food", "Hygiene & food safety"], salaryRange: "Rs. 40,000 - 70,000", status: "Open", createdAt: "2026-01-01T00:00:00.000Z" },
    { id: "JOB-rider", title: "Delivery Rider", department: "Delivery", type: "Full-time", location: "Renala Khurd / Okara", description: "Deliver orders quickly and safely across the service area.", requirements: ["Own bike + valid license", "Knows local routes", "Smartphone"], salaryRange: "Rs. 30,000 + fuel", status: "Open", createdAt: "2026-01-01T00:00:00.000Z" },
    { id: "JOB-cashier", title: "Cashier / Counter Staff", department: "Front of House", type: "Full-time", location: "Renala Khurd", description: "Handle billing, takeaway orders, and customer service at the counter.", requirements: ["Basic POS skills", "Good communication", "Honest & punctual"], salaryRange: "Rs. 28,000 - 40,000", status: "Open", createdAt: "2026-01-01T00:00:00.000Z" },
    { id: "JOB-server", title: "Waiter / Server", department: "Front of House", type: "Part-time", location: "Renala Khurd", description: "Serve dine-in guests and keep the seating area clean and welcoming.", requirements: ["Friendly attitude", "Team player", "Flexible hours"], salaryRange: "Rs. 25,000 - 35,000", status: "Open", createdAt: "2026-01-01T00:00:00.000Z" },
  ],
  branches: [
    { id: "renala-khurd-main", name: "Chicken House Main Branch", slug: "renala-khurd-main", status: "Active", manager: "", email: "info@chickenhouse.pk", phone: "+92 345 7493339", addressLine1: "Near Mitchell's, GT Road", addressLine2: "Close to Mitchell's Fruit Farm", city: "Renala Khurd, Okara", landmark: "Mitchell's Fruit Farm", coordinates: { lat: 0, lng: 0 }, timings: [], amenities: ["Family Seating", "Takeaway", "Delivery"], parkingAvailable: true, staffCount: 0, rating: 4.7, averageDailyOrders: 0, averageDailyRevenue: 0, gallery: [] },
  ],
  siteSettings: [
    { key: "default", brandName: "Chicken House", tagline: "A Symbol of Quality & Freshness", logoUrl: "", faviconUrl: "", primaryColor: "#7f1215", accentColor: "#d8a82f", contactEmail: "info@chickenhouse.pk", contactPhone: "+92 345 7493339", whatsappNumber: "923457493339", addressLine1: "Near Mitchell's, GT Road", city: "Renala Khurd, Okara", mapEmbedUrl: "", businessHours: [], socialLinks: [], seoTitle: "", seoDescription: "", maintenanceMode: false, settings: { currency: "PKR", timezone: "Asia/Karachi", twoFactorAuth: false, autoBackup: true, orderNotifications: true } },
  ],
  menu: clone(menuSeed),
});

declare global {
  // eslint-disable-next-line no-var
  var __chickenHouseDb__: ReturnType<typeof createDb> | undefined;
}

// Simple in-memory database for ERP
export const db = globalThis.__chickenHouseDb__ ?? createDb();

if (!globalThis.__chickenHouseDb__) {
  globalThis.__chickenHouseDb__ = db;
}
